### ISSUE TITLE
Genericify WebServiceTemplate.marshalSendAndReceive methods

### ISSUE THREAD

**Issue by sbelodon** [spring-projects/spring-ws#1247]
Hello! 
How about to implement https://github.com/spring-projects/spring-ws/issues/519 ?
jdk 1.4 is outdated now

**Comment by gregturn** [comment]
The problem is, we'd have to overhaul Spring OXM (Spring Framework). SOAP generally operates with a FooRequest/FooResponse nature, having two different types to represent the back and forth.

Spring OXM has this for unmarshalling a response:

```java
public interface Unmarshaller {
    boolean supports(Class<?> clazz);

    Object unmarshal(Source source) throws IOException, XmlMappingException;
}
```

This signature currently doesn't support providing a response type, and thus can't be overloaded. Until it has such a generic signature, Spring WS itself can't do anything. At least not without some risky type casting, which wouldn't make for a good design.

And to be honest, zooming out a bit, I see some flaws in attempting to alter these interfaces to support this. `public Object marshalSendAndReceive(String uri, final Object requestPayload)` (the current API) would require another argument of `Response` type. This is _almost_ the same as putting a cast into your own code.

To alter this requires a conversation with the Spring Framework team and whether or not they are willing to make such a change.
