### ISSUE TITLE
Upgrade to Axiom 1.4.

### ISSUE THREAD

**Issue by afattahi54** [spring-projects/spring-ws#1264]
Upgrade from axiom `1.2.2` to `1.3` or `1.4`

I face this error

````
java.lang.NoClassDefFoundError: org/apache/axiom/soap/impl/builder/StAXSOAPModelBuilder
	at org.springframework.ws.soap.axiom.AxiomSoapMessageFactory.createAxiomSoapMessage(AxiomSoapMessageFactory.java:273)
	at org.springframework.ws.soap.axiom.AxiomSoapMessageFactory.createWebServiceMessage(AxiomSoapMessageFactory.java:244)
	at org.springframework.ws.soap.axiom.AxiomSoapMessageFactory.createWebServiceMessage(AxiomSoapMessageFactory.java:85)
	at org.springframework.ws.transport.AbstractWebServiceConnection.receive(AbstractWebServiceConnection.java:89)
	at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:593)
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:542)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:394)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:388)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:378)

````

The `pom.xml` is:

````
<axiom.version>1.4.0</axiom.version>
........
<dependency>
	<groupId>org.apache.ws.commons.axiom</groupId>
	<artifactId>axiom-impl</artifactId>
	<version>${axiom.version}</version>
</dependency>
<dependency>
	<groupId>org.apache.ws.commons.axiom</groupId>
	<artifactId>axiom-api</artifactId>
	<version>${axiom.version}</version>
</dependency>

````

**Comment by gregturn** [comment]
What version of Spring Boot/Spring WS are you using?

**Comment by afattahi54** [comment]
It is the last version:

````
	<spring-ws.version>3.1.3</spring-ws.version>
	<spring-framework.version>5.3.23</spring-framework.version>
````

**Comment by gregturn** [comment]
A little digging has revealed the issue. Axiom 1.2 is based on Apache Geronimo (https://geronimo.apache.org/), particularly Geronimo Activation.

Axiom 1.3 has made a major upgrade to Jakarta Activation and other bits. Hence, Spring WS 3.x will never be compliant with that.

It appears Axiom made a release just recently (May 2022) for 1.4, with what must be Jakarta EE 9 support. Spring WS 4.0, in order to support Spring Boot 3.0, has also migrated to Jakarta EE 9. Last November, Spring WS started this migration path, and was forced to drop all Axiom support given their support was lacking.

Based on all this, I might be able to revisit bringing back Axiom support. It will take a little research to see if this is viable or not. But again, this will only be possible with Spring WS 4.0.

**Comment by gregturn** [comment]
Looks like Axiom 1.4 points at Jakarta EE 8, not 9, so no, we can't support this (yet).

**Comment by afattahi54** [comment]
Thanks dear @gregturn

I have see this link https://spring.io/blog/2017/10/30/spring-web-services-3-0-0-release-2-4-2-release-is-out which mentioned:

> Support for up-and-coming Axiom 1.3 (community contributor who wants to ensure Spring WS and Axiom 1.3 work together).

**Comment by gregturn** [comment]
I dug into that release, which was 5 years ago. That release included a patch to how SOAP headers were handled with Axiom, in anticipation of coming changes.

Turns out, a lot more was changed as well, making it non-trivial to pick up Axiom 1.3 (and 1.4 for that matter).

https://ws.apache.org/axiom/release-notes/1.3.0.html appears to have quite a lengthy listing of all the deprecated APIs removed from Axiom.

**Comment by gregturn** [comment]
A lot more digging, and after tinkering with all the changes in https://ws.apache.org/axiom/release-notes/1.3.0.html, it's possible to upgrade to Axiom 1.3/1.4. But it's not backwards compatible. There is no one set of APIs that works for both Axiom 1.2 and 1.3, meaning bumping a 3rd party dependency would require us to do such a change in either Spring WS 3.2 or 4.0.

Spring WS 4.0 is already aimed at supporting Spring Boot 3.0, which means we must be Jakarta EE 9 compatible. Axiom 1.3/1.4 points to some bits in Jakarta EE 8, meaning we can't take these changes to Spring WS 4.0.

This only leaves 3.2 as a viable way forward to supporting such a breaking change. Spring WS 3.1 has already passed OSS support, so I need to run this by my manager.

**Comment by gregturn** [comment]
We've decided to release Spring WS 3.2. That version is where you'll find support for Axiom 1.4.

This version of Spring WS won't be directly picked up by any version of Spring Boot due to standing maintenance policy. However, once released, it will be easy to pick up and we'll publish documentation showing how a one line statement in your build file will let you pick up this version when available.

**Comment by gregturn** [comment]
This issue has been reassessed. Instead of launching a brand new version, we are introducing support for Axiom 1.3+ on Spring WS's 3.1.x branch.

**Comment by gregturn** [comment]
Major thanks to @veithen for alerting me to the existence of `axiom-compat`. I was able to simplify the solution and easily demonstrate Spring WS's usage of axiom-1.2, axiom-1.3, and axiom-1.4, while ALSO verifying my axiom version detector operated properly thanks to you.
