### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by mpreziuso** [spring-projects/spring-ws#1288]
Is there a document outlining version compatibility across Spring projects?

As an example, I can [see](https://github.com/spring-projects/spring-ws/blob/f3471231709012dbeff469da27e72c529074ca7c/pom.xml#L116) spring-ws was compiled with spring-security 5.5.8 and I assume it'll probably be safe to upgrade spring-security to 5.5.9 (or greater 5.5.x) should there be a severe CVE in the future.

Would it be safe to upgrade to 5.6.x or 5.7.x?

Is there a documented approach on this?

**Comment by gregturn** [comment]
Yes, in general, you can upgrade to a newer patch release of the same generation of product (Spring Security 5.5 or Spring Framework 5.3). 

You can also see exactly what each version of Spring WS is tested against on our CI servers by looking here => https://github.com/spring-projects/spring-ws/blob/main/Jenkinsfile#L29-L130

This shows, for example, that Spring WS 3.1 is compiled against:
* Axiom 1.3 (vs. 1.2 as the default)
* Spring Framework snapshots (of the version we're on)
* Spring Security 5.6
* Spring Security 5.7
* On JDK 11
* On JDK 11 against Spring Framework snapshots
* on JDK 16 against Spring Framework snapshots

For Spring WS 3.1, we can't simply jump to the latest versions of Spring Framework/Security/etc. That would potentially break existing users. However, we test against a wide array of other combinations, giving you peace of mind should you wish to upgrade those components.

NOTE: Spring WS 3.1 does NOT build against Spring Framework 6. That requires upgrading to Spring WS 4.0.

Because these versions shift with some frequency, and we sometimes tune things, we don't have
